# Generated by Django 4.1.7 on 2023-03-05 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lieu', models.CharField(max_length=200)),
                ('Prix', models.IntegerField(default=0)),
                ('Date_published', models.DateField(auto_now_add=True, null=True)),
                ('is_already_occupied', models.BooleanField(default=False)),
                ('Surface_totale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_appartements', models.IntegerField(default=1)),
                ('hse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hse')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_appartements', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('Duree_location', models.TextField()),
                ('hse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hse')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_appartements', models.IntegerField(default=1)),
                ('caracteristiques', models.TextField()),
                ('Duree_location', models.TextField()),
                ('hse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hse')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Allocateurs(propriétaire d'HSE)",
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_appartements', models.IntegerField(default=1)),
                ('Duree_location', models.TextField()),
                ('hse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hse')),
            ],
        ),
        migrations.CreateModel(
            name='HSEreserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_reserved', models.DateField(auto_now_add=True)),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('HSEmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hse')),
            ],
        ),
        migrations.AddField(
            model_name='hse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.proprietaire'),
        ),
    ]
