# Generated by Django 4.1.7 on 2023-04-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=19)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TypeHSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=19)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.planimmobilier')),
            ],
        ),
    ]
